### ISSUE TITLE
RS Backend: FAPI compliance alignment from OB version v3.1.2

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#485]
### Description
From OB specification version v3.1.2, there have been changes to ensure alignment with FAPI Implementer's Draft 2.
- https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1077805207/Read+Write+Data+API+Specification+-+v3.1.2
``` shell
Changes for alignment with FAPI Implementer's Draft 2
- Replace references of `x-fapi-customer-last-logged-time` to `x-fapi-auth-date`
- Remove references of x-fapi-financial-id
```
- The header `x-fapi-financial-id` isn't mandatory.

The current implementation using java inheritance make simple to publish different versions of OB specs but from version 3.1.2 we need to review it to fix the FAPI headers.

### Current
From OB spec version v3.1.2 FAPI headers aren't aligned with FAPI Implementer's Draft 2.

### Expected
The OB spec, since version v3.1.2 are aligned with FAPI Implementer's Draft 2

### Tasks
- [x] Review and fix backoffice request mappings and controllers [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/tree/master/securebanking-openbanking-uk-rs-backoffice-api)
- [x] Review and fix obie apis [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/tree/master/securebanking-openbanking-uk-rs-obie-api)
- [x] Review and update postman tests
- [x] Review and update functional tests

### Acceptance criteria
- [x] All OB versions are aligned with FAPI
- [x] Backoffice controllers are update to be aligned with FAPI Implementer's Draft 2
- [x] All postman tests passed
- [x] All functional tests passed
