### ISSUE TITLE
As a TPP I want to be able to create a File Payment

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#543]
### Introduction

This feature allow TPP to create a **File Payment**

### User Story

As a TPP I wan to be able to create a **File Payment**

### Product requirements (optional)

- The TPP be able to initiate a **File Payment**
- The TPP be able to submit **File Payment**
- The TPP be able to get the initiation status
- The TPP be able to get the consent File
- The TPP be able to get the **File Payment** status
- The TPP be able to get the **File Payment** report file
- The TPP be able to get the **File Payment** details
- The **File Payment** APIs have test coverage (postman and functional tests) for all cases of operations

### Scope

- **Platform (configuration, initialiser)**
    - [x] #544
- **IG**
    - [x] #545
    - [x] #548
    - [x] #549
- **RCS Backend**
    - [x] #550
    - [x] #551
- **RCS User interfaces**
    - [x] #552
    - [x] #553
### File payment submitting
- **Platform (configuration, initialiser)**
    - [x] #554
- **IG**
    - [x] #555
- **RS backend**
    - [x] #556
    - [ ] #557
    - [ ] #558
### Tests and performance
- **Test support**
    - [x] #559
- **SBAT Postman coverage**
    - [x] #560
    - [x] #561
- **SBAT functional tests (uk spec) coverage**
    - [x] #562
    - [x] #563
### End tasks
- [x] #564

### Acceptance Criteria

- [x] All **File Payment consent** is implemented and have the proper unit tests and integration tests coverage
- [x] All implementation have:
    - [x] Postman tests coverage
    - [ ] Functional tests coverage
- [x] All **File Payment consent** postman tests pass
- [ ] All functional tests **File Payment consent** pass
- [ ] All **File Payment** `submit` / `status` / `report-file` and `get details` postman tests pass
- [ ] All **File Payment** `submit` / `status` / `report-file` and `get details` functional tests pass

**Comment by BohoCode** [comment]
This is done, but we have two issues still left to do, but they are optional so can be left for another time if required

#558 
#557
