### ISSUE TITLE
Review policy script handling of payment consents with Consumed status

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#574]
The policy script was updated to allow payment requests for consents with Consumed status to be authorised, see:
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/505

The logic was changed such that any request for a consent with status Authorised or Consumed is authorised by the policy script (subject to the request passing other checks).

This seems dangerous as a payment consent with status Consumed indicates that the consented action has been carried out. For a domestic payment this indicates that the payment has been submitted. See [spec](https://openbankinguk.github.io/read-write-api-site3/v3.1.10/resources-and-data-models/pisp/domestic-payment-consents.html#state-model)

Potential issues could arise if further requests to submit payments are made for the same consent, if it is in Consumed state then the requests should be rejected.

**Tasks**

- [ ] Review payments API calls and check which consent status they should allow
- [ ] Update policy script to tighten the status checking
- [ ] Update functional tests to do negative testing for combinations which are now disabled

**Comment by dbadham-fr** [comment]
Ultimately it is the job of the RS to reject additional payments being made for a consumed consent, as there could still be a race condition whereby 2 payment actions hit the policy check at the same time for the same consent before reaching the RS.

However it would be good to reject invalid requests as early in the flow as possible.

**Comment by dbadham-fr** [comment]
Closing as won't fix.

#1008 will remove the need for the policy script, the new Consent Store will handle consent status correctly.
