### ISSUE TITLE
Enable Java Bean Validation in RS simulator

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#578]
The OBIE datamodel code generated from the Read/Write swagger spec produces code annotated with [Java Bean Validation ](https://www.baeldung.com/javax-validation) annotations.

Guide to enabling this validation in spring boot [here](https://www.baeldung.com/spring-boot-bean-validation)

Currently, the RS simulator is not processing these annotations. This means that some key validations are not being done and TPPs may create consents & payments with invalid requests.

**Tasks**

- [x] Turn on Java Bean Validation in RS simulator
- [x] Ensure existing integration tests pass
- [x] Write negative tests which trigger validation failures (for a subset of the validation rules in the OBIE spec)
- [x] Review validation error handling, check HTTP responses for validation errors match the OBIE spec
- [ ] Run Postman collections and fix any data issues with request objects
