### ISSUE TITLE
As a TPP I want to be able to create a Funds Confirmation journey

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#598]
### Introduction

This feature allow TPP to create a **Funds Confirmation** (Card Based Payment Instrument Issuer (**CBPII**))

### User Story

As a TPP I want to be able to create a **Funds Confirmation**.

### Product requirements (optional)

- The TPP be able to initiate a **Funds Confirmation**
- The TPP be able to get the initiation status
- The PSU be able to revoke (delete) the consent initiation

| Operation | Endpoint | Spec |
|---|---|---|
| POST | /funds-confirmation-consents | [funds-confirmation-consent](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/cbpii/funds-confirmation-consent.html#endpoints) |
| GET | /funds-confirmation-consents/{ConsentId} | [funds-confirmation-consent](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/cbpii/funds-confirmation-consent.html#endpoints) |
| DELETE | /funds-confirmation-consents/{ConsentId} | [funds-confirmation-consent](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/cbpii/funds-confirmation-consent.html#endpoints) |

- The TPP be able make a request to confirm funds are available

| Operation | Endpoint | Spec |
|---|---|---|
| POST | /funds-confirmations | [funds-confirmation](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/cbpii/funds-confirmation.html#endpoints) |

### Confirmation of funds consent
- **Platform (configuration, initialiser)**
    - [x] ~#599~
- **IG**
    - [x] #600
    - [x] #601
- **RCS Backend**
    - [x] #1084 
    - [x] #602
    - [x] #603
- **RCS User interfaces**
    - [x] #604
    - [x] #605
### Confirmation of funds availability
- **IG**
    - [x] #606
- **RS backend**
    - [x] #1085 
    - [x] #1093
    - [x] ~#607~
#### Tests and performance
- **SBAT Postman coverage**
    - [x] #608
    - [x] #609
- **SBAT functional tests (uk spec) coverage**
    - [x] #610
    - [x] #611
- **End tasks**
    - [x] #612

### Acceptance Criteria
- [x] All **Funds Confirmation** is implemented and have the proper unit tests and integration tests coverage
- [x] All implementation have:
    - [x] Postman tests coverage
    - [x] Functional tests coverage
- [x] All **Funds Confirmation consent** postman tests pass
- [x] All functional tests **Funds Confirmation consent** pass
- [x] All **Funds Confirmation** availability postman tests pass
- [x] All **Funds Confirmation** availability functional tests pass

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/598?planning-poker) with Zenhub @jorgesanchezperez @dbadham-fr
