### ISSUE TITLE
RS backend: Refactoring the current implementation to retrieve the consent from IDM through IG using the platform client module.

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#607]
### Description
It will be necessary the refactoring of current implementation of `FundsConfirmationsApiController` to replace the Spring Bean Repository with a service to retrieve the consent from IDM instead of mongo.

**Ref:** https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/cbpii/funds-confirmation.html

### Tasks
- [ ] Replace the current `FundsConfirmationRepository` Spring bean with `ConsentService` to retrieve the consent from IDM through IG.
- [ ] Delete the unused headers (the authorisation header will be necessary to retrieve the consent from IDM)
> @See `FilePaymentFileValidationsController` to check how is used the `ConsentService` to retrieve an intent from IDM.

### Acceptance criteria
- [ ] The refactoring has been done and the consent is retrieve from IDM through IG.
- [ ] The solution has the proper test coverage
- [ ] All tests pass

**Comment by BohoCode** [comment]
No need to do this
