### ISSUE TITLE
Functional tests: Create Funds Confirmation availability

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#611]
### Description
Implement the proper functional tests to cover the Confirmation of funds availability resource flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [ ] Test coverage Confirmation of funds availability
  - [ ] Test coverage Confirmation of funds availability expected errors
  - [ ] Add gradle group task to run only the Confirmation of funds tests v3.1.8, v3.1.9, v3.1.10
### Acceptance criteria
- [ ] Postman tests work as expected

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/611?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez
