### ISSUE TITLE
Signature Algorithm: Remote Consent Service & secret store AM: keystore

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#625]
### Remote consent service
Currently we have defined a remote consent service in the `OAuth2 provider` (consent tab) with the remote consent agent ID `secure-open-banking-rcs` that redirects to RCS-ui application where the consent request signing algorithm is set as `RS256`
The FAPI [algorithm considerations](https://openid.net/specs/openid-financial-api-part-2-1_0.html#algorithm-considerations) for JWS, both clients and authorization servers define the below:
- shall use PS256 or ES256 algorithms;
- should not use algorithms that use RSASSA-PKCS1-v1_5 (e.g. RS256); and
- shall not use none.
 
### AM key secret store
Currently AM uses the global keystores created during deployment (installation) with keys for test purposes, the recommendation it's create a keystore with the keys that SBAT needs.
AM resolves the secret for the realm or globaly, the configured keystore in the realm have precedence of global configuration.
 
**(Ref.)Default Secret Stores in AM**
- Default global keystores are created during an installation: 
    - The `default-keystore` contains test keys. 
    - The `file-based default-password-store` contains the secret to access the `default-keystore`.
- There are no default secret stores in AM. 
AM creates a default keystore of type JCEKS when installing a fresh instance or during an upgrade. The default-keystore refers to the JCEKS file in the AM configuration directory tree, and it contains several test-only key aliases that are preconfigured.
To access the keys in the `default-keystore`, AM is configured to use files named `storepass` and `entrypass` that contain encrypted secret values that are saved in a file-based default store called `default-password-store`.

**Recomended**
For production deployments, generate a new keystore with the key aliases you need. 

## Tasks
- [ ] Discuss a solution to buid the SBAT keystore to be added to AM
    - [ ] Generate a new keystore for SBAT with the keys needed by SBAT
    - [ ] Configure AM to use the keystore for SBAT in the realm `alpha` 
    - [ ] Configure mapping for SBAT keystore key aliases set in the realm `alpha`
    - [ ] Fix algorithm for remote consent service `secure-open-banking-rcs`

**Comment by BohoCode** [comment]
Not required. FAPI conformance Advanced Part 1 suite tests now passing
