### ISSUE TITLE
Functional tests: Domestic VRP Payment consents

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#649]
### Description
Implement the proper functional tests to cover the domestic VRP payment consent flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage domestic VRP payment consent submission with all fields
  - [x] Test coverage domestic VRP payment consent submission with only mandatory fields
  - [x] Test coverage domestic VRP payment consent submission expected errors
  - [x] Add gradle group task to run only the domestic VRP payment consent tests v3.1.8
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `domestic VRP payment consent` functional tests pass.
- [x] As a developer I can run the a task to run only the `domestic VRP payment consent` functional tests v3.1.8

**Comment by mariantiris** [comment]
Branch name for domestic vrp consent tests: 649-domestic-vrp-consent-test
