### ISSUE TITLE
Functional tests: Domestic VRP Payment consents funds confirmation

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#650]
### Description
Implement the proper functional tests to cover the domestic VRP payment consent funds confirmation flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage domestic VRP payment consent funds confirmation with all fields
  - [x] Test coverage domestic VRP payment consent funds confirmation with only mandatory fields
  - [x] Test coverage domestic VRP payment consent funds confirmation expected errors
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `domestic VRP payment consent funds confirmation` functional tests pass.
- [x] As a developer I can run the a task to run only the `domestic VRP payment consent` including funds confirmation functional tests v3.1.8
