### ISSUE TITLE
Functional tests: Domestic VRP Payment order submission

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#651]
### Description
Implement the proper functional tests to cover the domestic VRP payment order submission flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage domestic VRP payment order submission with all fields
  - [x] Test coverage domestic VRP payment order submission with only mandatory fields
  - [x] Test coverage domestic VRP payment order submission expected errors
  - [x] Add gradle group task to run only the domestic VRP payment order submission tests v3.1.8
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `domestic VRP payment order` functional tests pass.
- [x] As a developer I can run the a task to run only the `domestic VRP payment order` functional tests v3.1.8
