### ISSUE TITLE
DCR add more negative test cases to conformance suite

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#654]
Additional tests to add:
- [x] DCR JWT which doesn't validate against signature
- [x] DCR JWT invalid signing algorithm used
- [x] SSA JWT which doesn't validate against signature
- [x] SSA JWT invalid signing algorithm used
- [x] Invalid redirect_uris in registration request (must match or be a subset of SSA urls)
