### ISSUE TITLE
FAPI confidential client authentication request jwt validation

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#676]
## Background:
FAPI spec: https://openid.net/specs/openid-financial-api-part-2-1_0.html#confidential-client

Example failing test: `fapi-rw-id2-ensure-request-object-without-scope-fails`
Description: 
> This test passes 'scope' only outside the request object. As FAPI-RW requires that all parameters are inside the signed request object, this test should end with the authorization server showing an error message that the request object is invalid (a screenshot of which should be uploaded) or with the user being redirected back to the conformance suite with a correct error response (invalid_request, invalid_request_object or access_denied). When using PAR, invalid_request_uri may also be returned, and the PAR endpoint call may return failure.

`scope` claim is not present in the JWT, instead it is supplied as a URL param.

An error response is expected from the authorization endpoint, instead an access token is returned.

## Tasks
Implement the following validation in IG (taken from the spec)
- shall include the request or request_uri parameter as defined in Section 6 of [OIDC](http://openid.net/specs/openid-connect-core-1_0.html) in the authentication request;
- shall send all parameters inside the authorization request's signed request object;
- shall additionally send duplicates of the response_type, client_id, and scope parameters/values using the OAuth 2.0 request syntax as required by Section 6.1 of the OpenID Connect specification if not using [PAR](https://tools.ietf.org/html/draft-ietf-oauth-par);
- shall send an exp claim in the request object that has a lifetime of no longer than 60 minutes;
- shall send a nbf claim in the request object;

Verify the following tests pass:

- [x] fapi-advanced-final-ensure-request-object-without-exp-fails
- [x] fapi1-advanced-final-ensure-request-object-without-nbf-fails
- [x] fapi-rw-id2-ensure-request-object-without-scope-fails
- [x] fapi-rw-id2-state-only-outside-request-object-not-used
- [x] fapi-rw-id2-ensure-request-object-without-nonce-fails
- [x] fapi-rw-id2-ensure-request-object-without-redirect-uri-fails
- [x] fapi-rw-id2-ensure-authorization-request-without-request-object-fails

**Comment by dbadham-fr** [comment]
There are several other tests which fail for the same reason, param must be present as a claim in the request JWT. All of the validations laid out in this section of the spec should be tackled as part of this issue.

AM would like to achieve FAPI compliance but this is likely to take some time to get this work prioritised. Therefore, we will implement these validations in IG for the time being.
