### ISSUE TITLE
Functional Tests: Fix VRP Debtor Account with existing user account

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#767]
Currently the VRP payment functional tests fails because the debtor account set in the request doesn't exist in RS and then RS raise an error.

Add support to set the debtor account from an existing account in RS in functional test.

### Task
- [x] Retrieve the user data from RS
- [x] Update existing test to set an existing user debtor account

### Acceptance criteria
- [x] All tests passed
