### ISSUE TITLE
Create and deploy new release deployment cluster

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureApiGateway/SecureApiGateway#768]
- [x] Create relenv cluster config and create cluster
### Helm:
- [x] Create new Chart repository called `secure-api-gateway-releases` (app of apps) - Contains the objects to deploy v1.0.0 of Secure API Gateway
- [ ] Add sub applications to create:
  - [x]  config map
  - [x] secret-manager
  - [x] cert-manager
  - [x] external secrets
  - [x] web-hook mutator
  - [x] prometheus
  - [x] nginx-ingress
  - [x] RCS
  - [x] RS
  - [x] RCS-UI
  - [x] Mongo
  - [ ] cs_config_manager - push config (one time only from pipeline?)

- [x] Create new Repository `secure-api-gateway-releases-deploy` - contains all the deployment code, e.g. pipelines, bash scripts

- [x] Create new Repository `secure-api-gateway-releases-deploy-specification` - overlay for ob-sandbox-vs deployment of Secure API Gateway v1.0.0
  - [ ]  Add Environment, Secrets and Variables (ESVs) for ob-sandbox-v1 cluster

## Documentation
- [ ] Document all Helm Chart values and kustomize overlay items - will do this post release when all charts etc have settled

## ToDo
- [x] Make secure-api-gateway-releases use helm definitions from artifactory
- [x] Push environment's secrets and variables (ESVs) to cluster - using new tool??? 
- [x] Use cs-config-manager to push config into FIdC
- [ ] Add cs-config-manager to deploy pipeline step
  - [ ] where do we get the cs-config-manager from?
  - [ ] Deploy config from fr-platform-config using tag v1.0.0 
  - [ ] Discuss how a customer would manage this config (override env vars in config)
- [x] Run and fix functional test issues
- [ ] Deployment tests??? - Test right certs are protecting endpoints etc.
- [x] DCR Conformance Suite tests
- [ ] FAPI Conformance tests
- [ ] Version (Tag) all deployment repos

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/768?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez @shaunharrisonFR
