### ISSUE TITLE
Version Java libraries and components action release (push to community repo in artifactory)

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#812]
## Description
Design the actions to release the artifacts as libraries and java components to be built and pushed to community repo in artifactory.

## ToDo: 
- [x] Review names of workflow secrets - these are also organisational secrets in Secure API Gateway and are used in the release github workflows
- [x] Tidy up secure-api-gateway-parent workflows (commits and step names etc)
- [x] Add missing secrets and tokens that the release workflows are dependent on to ob-ci-secrets. Update README with descriptions of what each secret is and agree names and layout were necessary i.e. if these are new secrets
- [x] Add package_helm and publish_helm to Makefile in repos that have helm charts:
  **Service artifacts**
  - [x] [RS secure-api-gateway-ob-uk-rs](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs)
      - Tag, java, docker, helm 
  - [x] [RCS secure-api-gateway-ob-uk-rcs](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs)
      -  Tag, java, docker, helm
  - [x] [RCS-UI secure-api-gateway-ob-uk-ui](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-ui)
      - Tag, docker, helm
  - [x] [IG secure-api-gateway-ob-uk](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk)
      - Tag, java, docker
  
  **Test artifacts**
  - [x] [test-initialiser](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-test-data-initializer)
      - Tag, Docker, helm
  - [x] [Uk functional tests](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-functional-tests)
      - Tag, Docker

   **Configuration and deployment artifacts**
  - [x] [fr-platform-config](https://github.com/SecureApiGateway/fr-platform-config)
      - Tag
  - [x] Docker image [conformance-dcr](https://github.com/SecureApiGateway/conformance-dcr)
  -  Update release workflow to create release tag and branch and release draft
      - [x] [secure-api-gateway-releases](https://github.com/SecureApiGateway/secure-api-gateway-releases)
          - Tag, Helm
      - [x] Helm chart only [secure-api-gateway-releases-helpers](https://github.com/SecureApiGateway/secure-api-gateway-releases-helpers) 
          - Tag, Helm
      - [secure-api-gateway-relenv-deployments](https://github.com/ForgeCloud/secure-api-gateway-relenv-deployments)
          - No workflow added: Tag manually to build the release
      - [secure-api-gateway-relenv-deployer](https://github.com/ForgeCloud/secure-api-gateway-relenv-deployer)
          - No workflow added: Tag manually to build the release
      - [sbat-infra](https://github.com/ForgeCloud/sbat-infra)
          - No workflow added: Tag manually to build the release
## Other tasks
- [x] Review how we release non-binary producing repos, e.g. fr-platfrom-config etc. 

### Release v1.0.0
- https://github.com/secureapigateway/secureapigateway/issues/927
