### ISSUE TITLE
Payment Submission does not work in v1.0.0

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#940]
**Affects Version/s:** 1.0.0

## Description
Payment Submission is broken. When submitting a valid payment that does not include optional fields in the initiation object, then payment submission fails with a 500 error. 

### Analysis of the cause
Currently the [policy evaluation script](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-fidc-initializer/blob/master/config/defaults/secure-open-banking/policy-evaluation-script.js) validate the request (payment submission) against the stored consent (payment initiation) making the deep compare.
- The consequences to make the deep compare
    - The consent stored initially is patched with new data when the user accepts the consent adding for example the values of `debtorAccount` field.
    - All consent fields stored are expected in the payment submission request object forcing non mandatory fields defined by the spec like as the `debtorAccount` to be mandatory in the request.

The policy script needs to focus his logic to validate the permissions to grant access a resource and It not to have the responsibility to make specific validations on the request object, the specific validations non regarding with the permissions must delegated to another service.

### Tasks
- [x] Clean up the policy evaluation script to validate only the permissions to grant access a resource (see https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-fidc-initializer/pull/179 in this issue)
- [x] Perform necessary validations of the initiation object in the test-faciltiy-bank #947 
- [x] Update postman tests to skip the request `get patched .... payment consent` to build the payment submission request
- [x] Change Functional Tests to supply the same Initiation object used in the consent request when making a payment submission (https://github.com/SecureApiGateway/SecureApiGateway/issues/955)

**Comment by frlaura-jianu** [comment]
- After removing the `initiationMatch` & `deepCompare` logic and running the functional tests, it seems that there is only one specific test failing, `shouldCreateDomesticVrp_throwsPolicyValidationErrorConsent_v3_1_10()` on the `Domestic VRPs` API, the one that was supposed to validate the `Initiation` object `request` vs. `consent`.

- The test was fixed. See PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-functional-tests/pull/114

- Still, the `Intiation` validation has to be done in RS, similar to the `Risk` validation previously implemented as a service in order to follow the OB spec: https://openbankinguk.github.io/read-write-api-site3/v3.1.10/resources-and-data-models/pisp/domestic-payments.html#notes

**Comment by BohoCode** [comment]
Applying the config to nightly to test the cs_config_manager work flow. 

In order to do that it will be necessary to:

- [x ] Disable the fidc-configurator (See https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-fidc-initializer/pull/182 above)
- [ ] Delete the policy script and the AISP and PISP policies. These were replaced by the fidc-configurator and have the wrong script ids, so will need to be deleted or they will prevent the scripts and policies from being created by the cs_config_manager
- [ ] run the cs-config-manager and have it push this config to nightly
- [ ] run the functional tests to ensure it all works.

**Comment by BohoCode** [comment]
Going to tag the fr-platform-config with 1.0.1

**Comment by BohoCode** [comment]
All good. There are some issues with using alpha-1 tag of cs-config-manager though. 

When trying to do a `fr-config-push secrets` for example I get the following error;
`replaceEnvSpecificValues is not a function`

Created a PR with a fix in (PR number 55)

**Comment by BohoCode** [comment]
Creating release;

https://github.com/SecureApiGateway/fr-platform-config/actions/runs/4809545231

**Comment by BohoCode** [comment]
While diagnosing failures in nightly I found that TPPs weren't being unregistered properly. Here's a fix for that.
