### ISSUE TITLE
v1.0.0 is missing some fields in the Payment's Risk Object for v3.1.10

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#948]
**Affects Version/s:** 1.0.0 

## Description
Currently the fields defined to store the Risk data in the managed objects support versions from 3.1.4 to 3.1.9.
```shell
"PaymentContextCode"
"MerchantCategoryCode"
"MerchantCustomerIdentification"
"DeliveryAddress"
```

To support the Risk data version 3.1.0 for initiation payments we need to add new non required fields:
```shell
"ContractPresentInidicator"
"BeneficiaryPrepopulatedIndicator"
"PaymentPurposeCode"
"BeneficiaryAccountType"
```

- https://openbankinguk.github.io/read-write-api-site3/v3.1.10/resources-and-data-models/pisp/domestic-payment-consents.html#domestic-payment-consent-request

**NOTE:** This will require an upgrade path

### Tasks
- [ ] Add new fields to payment managed objects
- [ ] Update groovy scripts to store the new fields values
- [ ] Test to ensure that the values are stored in the consent in IDM
- [ ] Ensure all tests passed (functional tests and postman)

**Comment by BohoCode** [comment]
We don't need this to fix the issue with v1.0.0 - This is a new unrelated issue that Jorge has found while adding validation of the initiation to the test-faciltiy-bank (rs).

**Comment by BohoCode** [comment]
Consents now managed by RS
